### ISSUE TITLE
Customizing Font

### ISSUE THREAD

**Issue by Arash-gm** [Kennyc1012/BottomSheetMenu#19]
is there any way to change menu items or title fonts?

**Comment by Kennyc1012** [comment]
See the Styling section of the README. You can change the text appearance which allows you to change the font styles. This does not, however, allow you to use an external font not found in android.

**Comment by Arash-gm** [comment]
@Kennyc1012 :  thank you for rapid response and yes i've read that and im using custom styling , however changing font doesn't work even with Calligraphy and its a huge downside. great work anyway

**Comment by Kennyc1012** [comment]
I have no plans to include this, but would consider a pull request.

**Comment by Kennyc1012** [comment]
This is now supported with the newly updated styles and XML fonts.

See [here](https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml) for adding a font via XML
