### ISSUE TITLE
open ShareBottomSheet  in two steps

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [Kennyc1012/BottomSheetMenu#41]
Hello. Is it possible to open the bottom sheet dialog in two steps? I mean when we touch a button,bottom sheet opens up to half of screen height and if the user sweeps it, it covers all screen height.
I am using createShareBottomSheet method

**Comment by AlirezaGhanbarinia** [comment]
any Help?
are you going to add this in next update?

**Comment by Kennyc1012** [comment]
Fixed with 3.0.0 release
