### ISSUE TITLE
customize dim background color

### ISSUE THREAD

**Issue by obraz** [Kennyc1012/BottomSheetMenu#47]
can make a dim background color customizable?

**Comment by Kennyc1012** [comment]
You would need to override the `android:windowBackground` attribute in the dialogs theme.

**Comment by obraz** [comment]
I tried
<style name="BottomSheetStyle" parent="@style/BottomSheet">
        <item name="bottom_sheet_bg_color">@android:color/white</item>
        <item name="android:windowBackground">@color/colorMainSeller</item>
    </style>

but it did not change anything

**Comment by Kennyc1012** [comment]
That's not how a style should be formatted, see the examples in the README

**Comment by obraz** [comment]
I updated my comment. android:windowBackground do not work

**Comment by Kennyc1012** [comment]
Should be fixed with 3.0.0 release
