### ISSUE TITLE
Bottom sheet with lot of content will cover whole screen?

### ISSUE THREAD

**Issue by ninonur** [Kennyc1012/BottomSheetMenu#51]
Bottom sheet with lot of content will cover whole screen. So can or should possibility adding such a maximum height? So I do this...
`BottomSheet build = new BottomSheet.Builder(this)
                            .setSheet(R.menu.bulk_option_menu)
                            .setListener(this)
                            .grid()
                            .create();
ViewGroup.LayoutParams param = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,200);
                    build.getLayout().setLayoutParams(param);`
But setlayoutparam returning java.lang.NullPointerException

**Comment by Kennyc1012** [comment]
The layout has not been created yet until the dialog is shown. I would set the layout params in the `onSheetShown(BottomSheet bottomSheet, Object object)` method of the listener

**Comment by Kennyc1012** [comment]
Fixed with 3.0.0 release
