### ISSUE TITLE
BottomSheet not anchoring to bottom of screen

### ISSUE THREAD

**Issue by iaindownie** [Kennyc1012/BottomSheetMenu#57]
On my emulator, BottomSheet works perfectly, anchored to bottom margin of screen. With the same code, on my device, there is a gap appearing between bottom of screen and bottom sheet. The sheet inflates a custom layout view, but there is nothing in the XML to suggest why a margin should appear, nor why different devices might render different end results. Any idea? I can post my XML...

Emulator
![emulator](https://user-images.githubusercontent.com/5167233/54069067-8a31a300-424b-11e9-8996-c09fea754f38.png)
Device
![device](https://user-images.githubusercontent.com/5167233/54069068-8c93fd00-424b-11e9-9deb-26f6aec48ec3.jpg)

**Comment by Kennyc1012** [comment]
The current version of BottomSheet no longer supports custom XML layouts, so I can not fix anything. I would suggest try using [BottomSheetDialog](https://developer.android.com/reference/android/support/design/widget/BottomSheetDialog) or [BottomSheetDialogFragment](https://developer.android.com/reference/android/support/design/widget/BottomSheetDialogFragment) from the support library

**Comment by iaindownie** [comment]
Thanks, I'll look into that.
