### ISSUE TITLE
how to show menu in State_Expanded when bottom sheet is shown in landscape mode?

### ISSUE THREAD

**Issue by allanckto** [Kennyc1012/BottomSheetMenu#61]
After upgrade to 3.x version, I created a bottom sheet menu on 10" tablet landscape orientation. I found that only bottom sheet title is shown and i need to swipe up the sheet to show all menu item.
But when i change orientation to portrait, it works perfectly.

How can i show all menu items when bottom sheet is shown when in landscape mode

**Comment by Kennyc1012** [comment]
Fixed in 3.1.3
