### ISSUE TITLE
Impossible to change font size?

### ISSUE THREAD

**Issue by kboirel** [Kennyc1012/BottomSheetMenu#63]
I tried to do what you say, in order to have a bigger font. But it's not working at all: 
"Cannot resolve symbol 'XXX'

Could you please help me to change the font size of item list please?

![image](https://user-images.githubusercontent.com/1890609/78114978-661aa400-7402-11ea-9985-85d5c0e25669.png)

**Comment by Kennyc1012** [comment]
Should be fixed with 3.1.2
