### ISSUE TITLE
QUERY_ALL_PACKAGES permission

### ISSUE THREAD

**Issue by SoreGaInochi** [Kennyc1012/BottomSheetMenu#70]
Hello,

First of all, thank you for this library. It's neat :)

This permission causes an error on Google Play:
"QUERY_ALL_PACKAGES: A permission for your app to see all the apps installed on a device. If it is not needed, you should remove it from your app."

Apparently, this was added some time ago, but I don't see the reason why this has been added. I've tested my app without this permission, and it works fine.

**Comment by Kennyc1012** [comment]
This permission is used for the createShareBottomSheet methods. It creates
a share dialog which queries the devices installed apps.

**Comment by SoreGaInochi** [comment]
Ah ok. I'll just remove it on my AndroidManifest in that case.

Thank you for your answer

**Comment by Kennyc1012** [comment]
As long as you are not calling those static methods, you are fine to remove
it. Ideally I should separate out those calls into a different module so
you can import it 8f needed.

**Comment by Kennyc1012** [comment]
Fixed with f73d7b51dce22234c4dcc8324a075c83f845e2e8
